### ISSUE TITLE
Yiimp pool not crediting

### ISSUE THREAD

**Issue by le2Ks** [NodeCoin-Dev/thor-core#1]
Hi

The yiimp pool is not crediting the miners for their found blocks, but does well receive the blocks though.

There is something in the debug.log file about  "Forge at work"

Its the same issue we had with the bees and litecoincash

Any idea how to fix this ?

I've tried :

- making a legacy wallet for the pool
- start the daemon with :
                                          - nominting=1
                                          - staking=0

Thought it might be because of that, but no success

Thanks

**Comment by NodeCoin-Dev** [comment]
This shiuld nit cause any issue as we use NOMP without any changes. It must
be a Yiimp issue only.

Le sam. 4 avr. 2020 9:07 PM, gnark-mining <notifications@github.com> a
écrit :

**Comment by Tastigernet** [comment]
in blocks.php after line 294 I added  
        // Adapt Thorcoin

        if ($category == 'created') {
            $block->category = 'immature';
            $block->save();
            continue;
        }
segwit is enabled, masternodes disabled
POW

Required this for the blocks to be recognized in the database, to be cleared and payouts to happen.

**Comment by le2Ks** [comment]
> in blocks.php after line 294 I added
> // Adapt Thorcoin
> 
> ```
>     if ($category == 'created') {
>         $block->category = 'immature';
>         $block->save();
>         continue;
>     }
> ```
> 
> segwit is enabled, masternodes disabled
> POW
> 
> Required this for the blocks to be recognized in the database, to be cleared and payouts to happen.

That solved it, thank you!
